name: Build Windows App

on:
  workflow_dispatch:   # Allows you to manually run this workflow

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: x86_64-pc-windows-msvc
          override: true

      - name: Build Windows Client
        working-directory: windows
        run: cargo build --release

      # Optional: Upload the built EXE as an artifact
      - name: Upload EXE
        uses: actions/upload-artifact@v4
        with:
          name: iranvpn-windows-x64
          path: windows/target/release/iran-vpn-windows.exe
